config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  resources :products do
    resources :comments
  end
  resources :users
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'new_user/sign_up'

  post 'payments/create'

  resources :charges
  resources :orders, only: [:index, :show, :create, :destroy]

   root :to => 'static_pages#landing_page'

     get 'products#:id' => 'catalog#view'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :comments
	has_many :orders
	validates :name, presence: true
	validates :description, presence: true
	validates :image_url, presence: true
	validates :color, presence: true
	validates :price, numericality: true
	def average_rating
		comments.average(:rating).to_f
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  respond_to :json, :html
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name ilike ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end
  # GET /products/1
  # GET /products/1.json
  def show

    @comments = @product.comments.order("created_at DESC")
    @comments = Comment.paginate(:page => params[:page])

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/static_pages/landing_page"}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-4 col-md-6">
      	<% @comments.each do |comment| %>
      	<hr>
      	<p>
          <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
          <% if signed_in? && current_user.admin? %>
            <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            	<% end %>
          </p>
      		<p><%= "Rating: #{comment.rating}/5" %></p>
      		<p><%= comment.body %></p>
      		<p class="rated"data-score="<%= comment.rating %>"</p>
		  </div>
    </div>
  </div>
</div>
<% end %>

</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="new-product">
<div class="panel panel-default">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
</div>
<div class="panel panel-default">
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
</div>
<div class="panel panel-default">
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
</div>
<div class="panel panel-default">
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, :value => (number_with_precision(f.object.price, :precision => 2) || 0) %>
  </div>
</div>
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    <i class="icon-ok icon-white"></i> Create Product
    <% end %>

<% end %>

app/views/products/_new_comment.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-4 col-md-6">
      <% if signed_in? %>
        <h4 class="form-heading">Add a review:</h4>
        <%= form_for([@product, @product.comments.build], remote:true) do |f| %>
          <p>
            <div class="rating form-group"></div>
          </p>

          <p class="form-group">
            <%= f.label :body, "Comments" %><br>
            <%= f.text_area :body %>
          </p>
          <p class="form-group">
            <%= f.submit "Submit", class: "btn btn-primary" %>
          </p>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="panel-content col-xs-2 col-md-5">
      <%= image_tag(product.image_url, class: "img-responsive", size: "500x650") %>
    </div>
    <div class="panel-body col-xs-4 col-md-7">
      <h1><%= link_to product.name, product %></h1>

      <p><%= product.description %></p>

      <p><%= product.color %></p>

      <p><%= product.price %></p>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div id="edprod">

  <h1>Editing Product</h1>

  <%= render 'form' %>


  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div id="productindex">
    <% @products.each do |product| %>
     <%= render product %>

  <% end %>


  <p class="newprodbutton btn btn-primary"><%= link_to 'New Product', new_product_path %></p>

</div>

app/views/products/new.html.erb
<div class="panel-heading">
  <h1>New Product</h1>
</div>
<div class="panel-body">
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-3 col-md-4">
      <%= image_tag("#{@product.image_url}", class: "img-thumbnail img-zoom", data_zoom_image: "#{@product.image_url}", size: "400x500") %>
    </div>
    <div id="prodlist" class="col-xs-3 col-md-8">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      <p>
	     <strong>Color:</strong>
	     <%= @product.color %>
      </p>
      <p>
	     <strong>Price:</strong>
	     <%= @product.price %>
      </p>
      </div>
    </div>
      <div class="row">
        <div id="stripebutton" class="col-xs-6 col-md-4">
          <%= form_tag "/payments/create" do %>
            <%= render partial: "shared/stripe_checkout_button" %>
            <%= hidden_field_tag(:product_id, @product.id) %>
          <% end %>
        </div>
        <div id="rating" class="col-xs-6 col-md-8">
          <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
          <p>
            <%= render 'new_comment' %>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-md-10 col-offset-2">
        <p>
          <%= render 'comments' %>
        </p>
        </div>
      </div>
    </div>
  <%= will_paginate @comments %>