config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }
  resources :products do
    resources :comments
  end
  resources :users
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  post 'new_user/sign_up'

  post 'payments/create'

  resources :charges
  resources :orders, only: [:index, :show, :create, :destroy]

   root :to => 'static_pages#landing_page'

     get 'products#:id' => 'catalog#view'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikes4u</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li class="navbar-brand"> <%= link_to "Bikes 4 U", static_pages_landing_page_path(:active => "static_pages_landing_page_path") %></li>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
          <li><%= link_to "About",  static_pages_about_path(@about) %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Order", orders_path(@orders) %></li>
          <li><%= link_to "Contact", static_pages_contact_path(@contact) %></li>
<li><%= link_to "Members", users_path(@users) %> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
        <div id="navsearch">
          <%= form_tag("/products", method: "get") do %>
          <%= label_tag(:q, "Search:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Submit", class: "btn btn-primary") %>
        <% end %>
        </div>
    </div>
  </div>
</nav>
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
<% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <div id="page-wrap">

    <%= yield %>
  </div><!-- /page-wrap-->
  <footer>
    <p>&copy; 2016 Bikes4U</p>
  </footer>
  </body>
</html>